Stop extending canvas when converting SVG to PNG
A larger canvas won't prevent clipping; if the inner elements of an SVG are
rendered larger than the specified width and height, they are still clipped at
the designated boundary. So we were extending and trimming for naught, and
wasting cycles doing so.

The optipng call is also parallelized now.

diff --git a/bin/collect b/bin/collect
--- a/bin/collect
+++ b/bin/collect
@@ -1,6 +1,6 @@
 #!/usr/bin/env zsh
 
-# Collect downloaded PNG images, crop, optimize, and put them into place.
+# Collect downloaded PNG images, optimize and put them into place.
 
 here=$0:A:h
 root=$here:h
@@ -11,25 +11,18 @@ downloads_dir=${DOWNLOADS_DIR:-$HOME/Downloads}
 mkdir -p $png_dir
 
 retval=0
+pngs=()
 for svg in $svg_dir/*.svg; do
     basename=${svg:t:r}@4x.png
-    original=$downloads_dir/$basename
-    dimensions="$(identify -format '%w %h' $original)" || {
-        echo "Error: Failed to identify ${(q-)original}" >&2
+    src=$downloads_dir/$basename
+    dst=$png_dir/$basename
+    [[ -f $src ]] || {
+        echo "Error: ${(q-)src} not found." >&2
         retval=1
         continue
     }
-    width=$dimensions[(w)1]
-    height=$dimensions[(w)2]
-    # Place the image in a larger, transparent canvas, then trim borders to get
-    # rid of any excess space in the original (which is due to discrepancies
-    # among different rendering engines; we assume the original isn't clipped
-    # due to underestimation).
-    output=$png_dir/$basename
-    (( width += 100 ))
-    (( height += 100 ))
-    convert $original -gravity center -background none -extent ${width}x${height} -trim +repage $output
-    optipng $output
-    rm $original
+    mv $src $dst
+    pngs+=$dst
 done
+parallel optipng ::: $pngs
 exit $retval
